name: Build and Publish Image

on:
  push:
    branches: [ "master", "main", "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_HOST }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKER_HOST }}/ankrgame/epoch-fighters-back
        tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./node.dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  update-prod:
    if: ${{ github.ref == 'refs/heads/main' ||  github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Update Production
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: rollout restart deploy mirage-epoch-fighters-back-main

  update-demo:
    if: ${{ github.ref == 'refs/heads/development' }}
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Update Demo
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: rollout restart deploy mirage-epoch-fighters-back-development
